<?php
declare(strict_types=1);

namespace LLTool\Install;

/**
 * Manages .env file configuration.
 */
final class EnvConfigurator
{
    /**
     * Write environment variables to .env file.
     */
    public static function write(array $data, bool $force = false): void
    {
        $path = self::envPath();

        if (file_exists($path) && !$force) {
            // Merge with existing .env
            $existing = self::read();
            $data = array_merge($existing, $data);
        }

        $content = self::generateEnvContent($data);
        file_put_contents($path, $content);
    }

    /**
     * Read existing .env file.
     */
    public static function read(): array
    {
        $path = self::envPath();
        
        if (!file_exists($path)) {
            return [];
        }

        $lines = file($path, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);
        $data = [];

        foreach ($lines as $line) {
            if (strpos(trim($line), '#') === 0) {
                continue;
            }

            if (strpos($line, '=') !== false) {
                [$key, $value] = explode('=', $line, 2);
                $key = trim($key);
                $value = trim($value);
                $value = trim($value, '"\'');
                $data[$key] = $value;
            }
        }

        return $data;
    }

    /**
     * Generate .env file content.
     */
    private static function generateEnvContent(array $data): string
    {
        $content = "# LLTool Environment Configuration\n";
        $content .= "# Generated by installer\n\n";

        // Application
        $content .= "# Application\n";
        $content .= "APP_ENV=" . ($data['APP_ENV'] ?? 'production') . "\n";
        $content .= "APP_DEBUG=" . ($data['APP_DEBUG'] ?? 'false') . "\n";
        $content .= "APP_URL=" . ($data['APP_URL'] ?? self::detectAppUrl()) . "\n\n";

        // Database (if exists) - Only database config goes in .env
        if (isset($data['DB_DRIVER'])) {
            $content .= "# Database Configuration\n";
            $content .= "DB_DRIVER=" . ($data['DB_DRIVER'] ?? 'mysql') . "\n";
            $content .= "DB_HOST=" . ($data['DB_HOST'] ?? 'localhost') . "\n";
            $content .= "DB_PORT=" . ($data['DB_PORT'] ?? '3306') . "\n";
            $content .= "DB_DATABASE=" . ($data['DB_DATABASE'] ?? '') . "\n";
            $content .= "DB_USERNAME=" . ($data['DB_USERNAME'] ?? '') . "\n";
            $content .= "DB_PASSWORD=" . ($data['DB_PASSWORD'] ?? '') . "\n\n";
        }

        // File Storage
        $content .= "# File Storage\n";
        $content .= "STORAGE_PATH=storage\n";
        $content .= "UPLOAD_MAX_SIZE=5242880\n";
        $content .= "ALLOWED_IMAGE_TYPES=jpg,jpeg,png,gif\n";

        return $content;
    }

    /**
     * Detect application URL.
     */
    private static function detectAppUrl(): string
    {
        $protocol = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https' : 'http';
        $host = $_SERVER['HTTP_HOST'] ?? 'localhost';
        return "{$protocol}://{$host}";
    }

    /**
     * Get .env file path.
     */
    private static function envPath(): string
    {
        // Try PHP directory first, then parent
        $phpDir = dirname(__DIR__, 2);
        $envPath = $phpDir . '/.env';
        
        // If not in PHP subdirectory, use current directory
        if (!file_exists($envPath) && file_exists(__DIR__ . '/../../.env')) {
            return __DIR__ . '/../../.env';
        }
        
        return $envPath;
    }
}

